## chapter-1: getting & knowing your data

In [1]:
import pandas as pd

In [ ]:
order_details=pd.read_csv(filepath_or_buffer="data.tsv.txt",sep="\t")

In [ ]:
order_details

In [12]:
order_details.shape

(4622, 5)

In [13]:
order_details.isnull().sum() #chain of functions or commands.

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [14]:
order_details.describe(include='all')

           order_id     quantity     item_name choice_description item_price
count   4622.000000  4622.000000          4622               3376       4622
unique          NaN          NaN            50               1043         78
top             NaN          NaN  Chicken Bowl        [Diet Coke]     $8.75
freq            NaN          NaN           726                134        730
mean     927.254868     1.075725           NaN                NaN        NaN
std      528.890796     0.410186           NaN                NaN        NaN
min        1.000000     1.000000           NaN                NaN        NaN
25%      477.250000     1.000000           NaN                NaN        NaN
50%      926.000000     1.000000           NaN                NaN        NaN
75%     1393.000000     1.000000           NaN                NaN        NaN
max     1834.000000    15.000000           NaN                NaN        NaN

In [15]:
order_details.dtypes

order_id              int64
quantity              int64
item_name               str
choice_description      str
item_price              str
dtype: object

In [16]:
order_details.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

## find out the items sold in the restaurents

In [ ]:
order_details.nunique()

In [ ]:
order_details['item_name']

In [ ]:
print(order_details['item_name'].unique())

In [ ]:
print(order_details['item_name'].nunique())

## give me the list of top 5 selling items.

In [ ]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending= False).head()

## give me the list of least 5 selling items.

In [ ]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending= True).head()

## chapter2 - data cleaning

In [ ]:
 order_details

In [ ]:
order_details.dtypes

In [ ]:
order_details[order_details["item_price"].str.contains(" ", na=False)]

In [ ]:
order_details.dtypes

In [ ]:
order_details.describe()

## TASK

1. FIND OUT THE TOP 5 SELLING ITEMS INDIVIDUAL REVENUE IT MADE.
2. TOTAL REVENUE OF THE TOP 5 ITEMS SOLD.

In [ ]:
order_details

In [ ]:
order_details = pd.DataFrame(order_details)

In [ ]:
print(type(order_details))

In [ ]:
order_details

In [ ]:
order_details

In [ ]:
order_details=pd.read_csv(filepath_or_buffer="data.tsv.txt",sep="\t")
order_details

In [ ]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending= True).head()

In [ ]:
order_details.groupby(by="item_name")["quantity"].sum().sort_values(ascending= False).head()

In [ ]:
order_details["item_price"] = (
    order_details["item_price"]
    .astype(str)
    .str.replace("$", "", regex=False)
    .str.split()
    .str[0]
    .astype(float)
)
order_details.dtypes

In [ ]:
order_details["revenue"] = (
    order_details["quantity"] * order_details["item_price"]
)

In [ ]:
item_revenue = (
    order_details
    .groupby("item_name")
    .agg(
        total_quantity=("quantity", "sum"),
        individual_revenue=("revenue", "sum")
    )
    .reset_index()
)

In [ ]:
top_5_items = (
    item_revenue
    .sort_values(by="individual_revenue", ascending=False)
    .head(5)
)

print(top_5_items)

In [ ]:
total_revenue_top_5 = top_5_items["individual_revenue"].sum()
print("Total revenue of top 5 items:", total_revenue_top_5)

## chapter 3
*1D - Series

*2D - Data frame

In [15]:
pd.Series(data=(["Name","prasanth","sethu","jam","priya","dragon"],["age",18,20,24,24,23],))

0    [Name, prasanth, sethu, jam, priya, dragon]
1                      [age, 18, 20, 24, 24, 23]
2                                              ,
dtype: object

In [8]:
pd.DataFrame(data={"Name":["prasanth","sethu","jam","priya","dragon","murali"],
                   "age":[18,20,24,24,23,32],
                   "sex":["male","male","male","female","female","male"],
                   "Department":["bca","mca","bsc","b,com","b.tech","engi"],
                   "course fee":[18000,20000,30000,40000,50000,60000],
                   "contact":[9876543289,2345678769,2345678879,3456789645,3456790985,4567898765],
                   "location":["chennai","salem","goa","pondi","madurai","tnagar"]})

       Name  age     sex Department  course fee     contact location
0  prasanth   18    male        bca       18000  9876543289  chennai
1     sethu   20    male        mca       20000  2345678769    salem
2       jam   24    male        bsc       30000  2345678879      goa
3     priya   24  female      b,com       40000  3456789645    pondi
4    dragon   23  female     b.tech       50000  3456790985  madurai
5    murali   32    male       engi       60000  4567898765   tnagar

## chapter 4 - Filtering & Selection & Sorting

In [2]:
Euro_stats_data=pd.read_csv(filepath_or_buffer="Euro_2012_stats_TEAM.csv")
Euro_stats_data

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
6,Greece,5,8,18,30.7%,19.2%,32,1,1,1,...,13,65.1%,67,48,12,9,1,12,12,20
7,Italy,6,34,45,43.0%,7.5%,110,2,0,0,...,20,74.1%,101,89,16,16,0,18,18,19
8,Netherlands,2,12,36,25.0%,4.1%,60,2,0,0,...,12,70.6%,35,30,3,5,0,7,7,15
9,Poland,2,15,23,39.4%,5.2%,48,0,0,0,...,6,66.7%,48,56,3,7,1,7,7,17
10,Portugal,6,22,42,34.3%,9.3%,82,6,0,0,...,10,71.5%,73,90,10,12,0,14,14,16
11,Republic of Ireland,1,7,12,36.8%,5.2%,28,0,0,0,...,17,65.4%,43,51,11,6,1,10,10,17
12,Russia,5,9,31,22.5%,12.5%,59,2,0,0,...,10,77.0%,34,43,4,6,0,7,7,16
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18
14,Sweden,5,17,19,47.2%,13.8%,39,3,0,0,...,8,61.6%,35,51,7,7,0,9,9,18
15,Ukraine,2,7,26,21.2%,6.0%,38,0,0,0,...,13,76.5%,48,31,4,5,0,9,9,18

In [19]:
Euro_stats_data.columns

Index(['Team', 'Goals', 'Shots on target', 'Shots off target',
       'Shooting Accuracy', '% Goals-to-shots', 'Total shots (inc. Blocked)',
       'Hit Woodwork', 'Penalty goals', 'Penalties not scored', 'Headed goals',
       'Passes', 'Passes completed', 'Passing Accuracy', 'Touches', 'Crosses',
       'Dribbles', 'Corners Taken', 'Tackles', 'Clearances', 'Interceptions',
       'Clearances off line', 'Clean Sheets', 'Blocks', 'Goals conceded',
       'Saves made', 'Saves-to-shots ratio', 'Fouls Won', 'Fouls Conceded',
       'Offsides', 'Yellow Cards', 'Red Cards', 'Subs on', 'Subs off',
       'Players Used'],
      dtype='str')

In [27]:
filter_euro_data=Euro_stats_data[['Team','Goals','Shooting Accuracy','Penalty goals','Penalties not scored','Offsides']]
filter_euro_data

,Team,Goals,Shooting Accuracy,Penalty goals,Penalties not scored,Offsides
0,Croatia,4,51.9%,0,0,2
1,Czech Republic,4,41.9%,0,0,8
2,Denmark,4,50.0%,0,0,8
3,England,5,50.0%,0,0,6
4,France,3,37.9%,0,0,5
5,Germany,10,47.8%,1,0,12
6,Greece,5,30.7%,1,1,12
7,Italy,6,43.0%,0,0,16
8,Netherlands,2,25.0%,0,0,3
9,Poland,2,39.4%,0,0,3
10,Portugal,6,34.3%,0,0,10
11,Republic of Ireland,1,36.8%,0,0,11
12,Russia,5,22.5%,0,0,4
13,Spain,12,55.9%,1,0,19
14,Sweden,5,47.2%,0,0,7
15,Ukraine,2,21.2%,0,0,4

In [16]:
filter_euro_data.sort_values(['Shooting Accuracy'],ascending=False).head()

       Team  Goals Shooting Accuracy  Penalty goals  Penalties not scored
13    Spain     12             55.9%              1                     0
0   Croatia      4             51.9%              0                     0
2   Denmark      4             50.0%              0                     0
3   England      5             50.0%              0                     0
5   Germany     10             47.8%              1                     0

In [17]:
filter_euro_data.sort_values(['Shooting Accuracy'],ascending=True).head()

           Team  Goals Shooting Accuracy  Penalty goals  Penalties not scored
15      Ukraine      2             21.2%              0                     0
12       Russia      5             22.5%              0                     0
8   Netherlands      2             25.0%              0                     0
6        Greece      5             30.7%              1                     1
10     Portugal      6             34.3%              0                     0

In [19]:
filter_euro_data[filter_euro_data['Penalty goals']==1]

       Team  Goals Shooting Accuracy  Penalty goals  Penalties not scored
5   Germany     10             47.8%              1                     0
6    Greece      5             30.7%              1                     1
13    Spain     12             55.9%              1                     0

In [23]:
filter_euro_data.sort_values(['Goals'],ascending=True).head()

,Team,Goals,Shooting Accuracy,Penalty goals,Penalties not scored
11,Republic of Ireland,1,36.8%,0,0
8,Netherlands,2,25.0%,0,0
9,Poland,2,39.4%,0,0
15,Ukraine,2,21.2%,0,0
4,France,3,37.9%,0,0

In [30]:
filter_euro_data[filter_euro_data['Offsides']<=10]

,Team,Goals,Shooting Accuracy,Penalty goals,Penalties not scored,Offsides
0,Croatia,4,51.9%,0,0,2
1,Czech Republic,4,41.9%,0,0,8
2,Denmark,4,50.0%,0,0,8
3,England,5,50.0%,0,0,6
4,France,3,37.9%,0,0,5
8,Netherlands,2,25.0%,0,0,3
9,Poland,2,39.4%,0,0,3
10,Portugal,6,34.3%,0,0,10
12,Russia,5,22.5%,0,0,4
14,Sweden,5,47.2%,0,0,7
15,Ukraine,2,21.2%,0,0,4

## Chapter -5 How To Deal With Missing Values.

In [66]:
sharp_sys=pd.read_csv("employee_data.csv")
sharp_sys

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
1    Nasir  31.0    IT Tech      NaN  12-11-2020
2  Mathiew   NaN    Support  58000.0  15-01-2025
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023
6      NaN  40.0         IT  64000.0  10-09-2022
7    Nasir  31.0    IT Tech      NaN  12-11-2020

### Step 1: I'll call to my client, and check with him if he can give the right data - great!!!

incase client is asking to perform the data cleaning opreators.

### step - 1 remove duplicate values.

In [67]:
sharp_sys=sharp_sys.drop_duplicates(inplace=False)

In [83]:
sharp_sys

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

### step-2: find out the null entries.

In [84]:
sharp_sys=sharp_sys.dropna()
sharp_sys

      Name   Age Department   Salary   Join_Date
0   Rajesh  29.0        Ops  60000.0  21-05-2023
3  Gilbert  29.0        Ops  60000.0  21-05-2021
4    Kevin  28.0    Support  61000.0  30-07-2024
5    Navin  35.0    Support  72000.0  19-08-2023

In [74]:
sharp_sys.shape

(4, 5)

#### step- 3 record in a document.
* client gave totally 7 obsevations out of which 3 entries are remove because records do not have complete information

#### step-4 get approval
* send this to client and get approval to proceed for model buliding or model training

In [87]:
sharp_sys.isnull().sum()

Name          0
Age           0
Department    0
Salary        0
Join_Date     0
dtype: int64

### level -2 data cleaning